<main>
    <section>
        <h1>Notre équipe</h1>
        <article class="clearfix">
            <h2>Amélie, fondatrice de Cup of Tea</h2>
            <hr>
            <img class="img-responsive left" src="img/amelie.jpg" title="Amélie" alt="Amélie" width="500" height="334">
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
        </article>
        <article class="clearfix">
            <h2>Xavier, fondateur de Cup of Tea</h2>
            <hr>
            <img class="img-responsive right" src="img/xavier.jpg" title="Amélie" alt="Amélie" width="500" height="281">
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
        </article>
        <h1>Notre concept</h1>
        <article>
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <p>
                Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                opperientes.
                Raptim igitur properantes ut motus sui rumores celeritate nimia praevenirent,
                vigore corporum ac levitate confisi per flexuosas semitas ad summitates collium tardius evadebant.
                Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
        </article>
        <nav class="concepts">
            <div class="concept">
                <figure>
                    <img class="img-responsive" src="img/concept/1.svg" alt="Tea" title="Tea" width="50" height="50">
                    <figcaption>Lorem ipsum</figcaption>
                </figure>
                <p>
                    Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                    sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
            <div class="concept">
                <figure>
                    <img class="img-responsive" src="img/concept/2.svg" alt="Like" title="Like" width="50" height="50">
                    <figcaption>Dolor sit</figcaption>
                </figure>
                <p>
                    Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                    sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
            <div class="concept">
                <figure>
                    <img class="img-responsive" src="img/concept/3.svg" alt="Happy" title="Happy" width="50"
                         height="50">
                    <figcaption>Amet</figcaption>
                </figure>
                <p>
                    Arbitrabantur enim nullo inpediente transgressi inopino adcursu adposita quaeque vastare,
                    sed in cassum labores pertulere gravissimos. Lorem ipsum sit amet, consectetur adipiscing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
        </nav>
    </section>
</main>