<main>
    <section id="offer">
        <h1>C'est Noël chez Cup of Tea, profitez-en !</h1>
        <figure>
            <img class="img-responsive" src="img/offre-noel.jpg" title="Offre Noël" alt="Offre Noël" width="1366"
                 height="220">
            <figcaption>Pour toute commande effectuée avant le 20 décembre</figcaption>
        </figure>
    </section>
    <section class="tea">
        <h2>Choisissez votre thé</h2>
        <hr>
        <div id="tea">
            <div class="twice">
                <figure>
                    <a href="listing.php#blackTea"><img class="img-responsive" src="img/tea/1.jpg" title="Thé noir"
                                                        alt="Thé noir" width="150"
                                                        height="140"></a>
                    <figcaption><a href="listing.php#blackTea">Thé noir</a></figcaption>
                </figure>
                <figure>
                    <a href="listing.php#greenTea"><img class="img-responsive" src="img/tea/2.jpg" title="Thé vert"
                                                        alt="Thé vert" width="150"
                                                        height="140"></a>
                    <figcaption><a href="listing.php#greenTea">Thé vert</a></figcaption>
                </figure>
            </div>
            <div class="twice">
                <figure>
                    <a href="listing.php#oolong"><img class="img-responsive" src="img/tea/3.jpg" title="Oolong" alt="Oolong"
                                                      width="150" height="140"></a>
                    <figcaption><a href="listing.php#oolong">Oolong</a></figcaption>
                </figure>
                <figure>
                    <a href="listing.php#whiteTea"><img class="img-responsive" src="img/tea/4.jpg" title="Thé blanc"
                                                        alt="Thé blanc" width="150"
                                                        height="140"></a>
                    <figcaption><a href="listing.php#whiteTea">Thé blanc</a></figcaption>
                </figure>
            </div>
            <div class="once">
                <figure>
                    <a href="listing.php#rooibos"><img class="img-responsive" src="img/tea/5.jpg" title="Rooibos"
                                                       alt="Rooibos" width="150" height="140"></a>
                    <figcaption><a href="listing.php#rooibos">Rooibos</a></figcaption>
                </figure>
            </div>
        </div>
    </section>
    <section class="show">
        <div id="show">
            <article>
                <h2>Notre nouveauté</h2>
                <hr>
                <figure>
                    <img class="img-responsive" src="img/product/product1.jpg" title="Thé du hammam" alt="Thé du hammam"
                         width="287" height="287">
                    <figcaption>Thé du hammam</figcaption>
                </figure>
                <p>
                    Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                    qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                    opperientes.
                </p>
                <p>À partir de <span class="price">8,50€</span></p>
                <a class="see" href="listing.php#hammam">Voir ce produit</a>
            </article>
            <article>
                <h2>Notre best-seller</h2>
                <hr>
                <figure>
                    <img class="img-responsive" src="img/product/product2.jpg" title="Infusion Herboriste"
                         alt="Infusion Herboriste" width="287" height="287">
                    <figcaption>Infusion Herboriste</figcaption>
                </figure>
                <p>
                    Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                    qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                    opperientes.
                </p>
                <p>À partir de <span class="price">7,60€</span></p>
                <a class="see" href="#">Voir ce produit</a>
            </article>
            <article>
                <h2>Notre coup de coeur</h2>
                <hr>
                <figure>
                    <img class="img-responsive" src="img/product/product3.jpg" title="Blue of London" alt="Blue of London"
                         width="287" height="287">
                    <figcaption>Blue of London</figcaption>
                </figure>
                <p>
                    Et cum superatis difficultatibus arduis ad supercilia venissent fluvii Melanis alti et verticosi,
                    qui pro muro tuetur accolas circumfusus, augente nocte adulta terrorem quievere paulisper lucem
                    opperientes.
                </p>
                <p>À partir de <span class="price">9,00€</span></p>
                <a class="see" href="listing.php#blueLondon">Voir ce produit</a>
            </article>
        </div>
    </section>
</main>