<main>
    <section id="blackTea" class="listing clearfix">
        <img class="img-responsive" src="img/tea/1.jpg" title="Thé noir" alt="Thé noir" width="150" height="140">
        <h2>Thé noir</h2>
        <hr>
        <p>
            Le thé noir, que les chinois appellent thé rouge en référence à la couleur cuivrée de son infusion,
            est un thé complètement oxydé. La fabrication du thé noir se fait en cinq étapes :
            le flétrissage, le roulage, l'oxydation, la torréfaction et le triage.
            Cette dernière opération permet de différencier les différents grades.
        </p>
        <div class="article">
            <article>
                <figure>
                    <figcaption>Blue of london</figcaption>
                    <img class="img-responsive" src="img/product/product3_big.jpg" title="Blue of london"
                         alt="Blue of london" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">7,50€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[0] ?>&$src=<?= $src[0] ?>&$price=<?= $price[0] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Thé des lords</figcaption>
                    <img class="img-responsive" src="img/product/product6_big.jpg" title="Thé des lords" alt="Thé des lords"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">8,20€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[1] ?>&$src=<?= $src[1] ?>&$price=<?= $price[1] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Thé des vahinés</figcaption>
                    <img class="img-responsive" src="img/product/product7_big.jpg" title="Thé des vahinés"
                         alt="Thé des vahinés" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">7,50€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[2] ?>&$src=<?= $src[2] ?>&$price=<?= $price[2] ?>">Voir ce produit</a>
            </article>
        </div>
    </section>
    <section id="greenTea" class="listing clearfix">
        <img class="img-responsive" src="img/tea/2.jpg" title="Thé vert" alt="Thé vert" width="150" height="140">
        <h2>Thé vert</h2>
        <hr>
        <p>
            Réputé pour ses nombreuses vertus grâce à sa richesse en antioxydants, le thé vert déshaltère, tonifie,
            apaise, fortifie, et procure une incontestable sensation de bien-être. Délicat et peu amer,
            il est apprécié à tout moment de la journée et propose une palette d'arômes très variés : végétal,
            minéral, floral, fruité.
        </p>
        <div class="article">
            <article id="hammam">
                <figure>
                    <figcaption>Thé du hammam</figcaption>
                    <img class="img-responsive" src="img/product/product1_big.jpg" title="Thé du hammam" alt="Thé du hammam"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">8,40€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[3] ?>&$src=<?= $src[3] ?>&$price=<?= $price[3] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Vive le thé !</figcaption>
                    <img class="img-responsive" src="img/product/product4_big.jpg" title="Vive le thé !" alt="Vive le thé !"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">9,30€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[4] ?>&$src=<?= $src[4] ?>&$price=<?= $price[4] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Thé des alizés</figcaption>
                    <img class="img-responsive" src="img/product/product5_big.jpg" title="Thé des alizés"
                         alt="Thé des alizés" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">7,50€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[5] ?>&$src=<?= $src[5] ?>&$price=<?= $price[5] ?>">Voir ce produit</a>
            </article>
        </div>
    </section>
    <section id="oolong" class="listing clearfix">
        <img class="img-responsive" src="img/tea/3.jpg" title="Oolong" alt="Oolong" width="150" height="140">
        <h2>Oolong</h2>
        <hr>
        <p>
            Les Oolong, que les chinois appellent thé bleu-vert en référence à la couleur de leurs feuilles infusées,
            sont des thés semi-oxydés : leur oxydation n'a pas été menée à son terme. Spécialités de Chine et de Taïwan,
            il en existe une grande variété, en fonction de la région de culture,
            de l'espèce du théier ou encore du processus de fabrication.
        </p>
        <div class="article">
            <article>
                <figure>
                    <figcaption>Vive les fetes</figcaption>
                    <img class="img-responsive" src="img/product/product8_big.jpg" title="Vive les fetes"
                         alt="Vive les fetes" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">11,10€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[6] ?>&$src=<?= $src[6] ?>&$price=<?= $price[6] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Fleur d'oranger Oolong</figcaption>
                    <img class="img-responsive" src="img/product/product9_big.jpg" title="Fleur d'oranger Oolong"
                         alt="Fleur d'oranger Oolong" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">10,90€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[7] ?>&$src=<?= $src[7] ?>&$price=<?= $price[7] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Oolong 7 agrumes</figcaption>
                    <img class="img-responsive" src="img/product/product10_big.jpg" title="Oolong 7 agrumes"
                         alt="Oolong 7 agrumes"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">13,20€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[8] ?>&$src=<?= $src[8] ?>&$price=<?= $price[8] ?>">Voir ce produit</a>
            </article>
        </div>
    </section>
    <section id="whiteTea" class="listing clearfix">
        <img class="img-responsive" src="img/tea/4.jpg" title="Thé blanc" alt="Thé blanc" width="150" height="140">
        <h2>Thé blanc</h2>
        <hr>
        <p>
            Le thé blanc est une spécialité de la province du Fujian. De toutes les familles de thé,
            c'est celle dont la feuille est la moins transformée par rapport à son état naturel. Non oxydé,
            le thé blanc ne subit que deux opérations : un flétrissage et une dessiccation.
            Il existe deux grands types de thé blanc : les Aiguilles d'Argent et les Bai Mu Dan.
        </p>
        <div class="article">
            <article>
                <figure>
                    <figcaption>Thé des songes blanc</figcaption>
                    <img class="img-responsive" src="img/product/product11_big.jpg" title="Thé des songes blanc"
                         alt="Thé des songes blanc" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">12,00€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[9] ?>&$src=<?= $src[9] ?>&$price=<?= $price[9] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Bai mu dan</figcaption>
                    <img class="img-responsive" src="img/product/product12_big.jpg" title="Bai mu dan" alt="Bai mu dan"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">9,50€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[10] ?>&$src=<?= $src[10] ?>&$price=<?= $price[10] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Aiguilles d'argent</figcaption>
                    <img class="img-responsive" src="img/product/product13_big.jpg" title="Aiguilles d'argent"
                         alt="Aiguilles d'argent"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">47,20€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[11] ?>&$src=<?= $src[11] ?>&$price=<?= $price[11] ?>">Voir ce produit</a>
            </article>
        </div>
    </section>
    <section id="rooibos" class="listing clearfix">
        <img class="img-responsive" src="img/tea/5.jpg" title="Thé noir" alt="Thé noir" width="150" height="140">
        <h2>Rooibos</h2>
        <hr>
        <p>
            Le Rooibos (appelé thé rouge bien qu'il ne s'agisse pas de thé)
            est une plante poussant uniquement en Afrique du Sud et qui ne contient pas du tout de théine.
            Son infusion donne une boisson très agréable, ronde et légèrement sucrée. Riche en antioxydants,
            faible en tanins et dénué de théine, le Rooibos peut être dégusté en journée comme en soirée.
        </p>
        <div class="article">
            <article>
                <figure>
                    <figcaption>Rooibos à la verveine</figcaption>
                    <img class="img-responsive" src="img/product/product14_big.jpg" title="Rooibos à la verveine"
                         alt="Rooibos à la verveine" width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">7,00€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[12] ?>&$src=<?= $src[12] ?>&$price=<?= $price[12] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Spicy Passion</figcaption>
                    <img class="img-responsive" src="img/product/product15_big.jpg" title="Spicy Passion"
                         alt="Spicy Passion"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">9,00€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[13] ?>&$src=<?= $src[13] ?>&$price=<?= $price[13] ?>">Voir ce produit</a>
            </article>
            <article>
                <figure>
                    <figcaption>Rooibos des amants</figcaption>
                    <img class="img-responsive" src="img/product/product16_big.jpg" title="Rooibos des amants"
                         alt="Rooibos des amants"
                         width="450" height="450">
                </figure>
                <p>
                    À partir de <span class="price">8,20€</span>
                </p>
                <a class="see" href="product.php?$name=<?= $name[14] ?>&$src=<?= $src[14] ?>&$price=<?= $price[14] ?>">Voir ce produit</a>
            </article>
        </div>
    </section>
</main>