<main>
	<section id="product">
		<h1><?= $name ?></h1>
		<figure>
            <img class="img-responsive" src="<?= $src ?>" title="<?= $name ?>"
                 alt="<?= $name ?>" width="450" height="450">
			<figcaption>
                <span class="price"><?= $price ?></span>
                <br>
                <a class="see" href="#">Ajouter au panier</a>
            </figcaption>
        </figure>
	</section>
</main>